'use client';
import StrategyArchiveScreen from './StrategyArchiveScreen';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {linkedObjects,type StrategyData} from '../lib/strategy';
function arrowShape(from:{x:number;y:number},to:{x:number;y:number}){
 const dx=to.x-from.x,dy=to.y-from.y,d=Math.hypot(dx,dy)||1,ux=dx/d,uy=dy/d;
 const a={x:from.x+ux*22,y:from.y+uy*22},b={x:to.x-ux*26,y:to.y-uy*26};
 const bend=Math.min(70,d*.18),c={x:(a.x+b.x)/2-uy*bend,y:(a.y+b.y)/2+ux*bend};
 const point=(t:number)=>({x:(1-t)**2*a.x+2*(1-t)*t*c.x+t*t*b.x,y:(1-t)**2*a.y+2*(1-t)*t*c.y+t*t*b.y});
 const side=(t:number,w:number)=>{const q=point(t),vx=2*((1-t)*(c.x-a.x)+t*(b.x-c.x)),vy=2*((1-t)*(c.y-a.y)+t*(b.y-c.y)),n=Math.hypot(vx,vy)||1;return `${q.x-vy/n*w},${q.y+vx/n*w}`};
 const headT=Math.max(.55,1-24/d),tail=Math.min(13,d*.075),points=[];
 for(let i=0;i<=24;i++){const t=headT*i/24;points.push(side(t,4+(tail-4)*(1-t/headT)**2));}
 points.push(side(headT,15),`${b.x},${b.y}`,side(headT,-15));
 for(let i=24;i>=0;i--){const t=headT*i/24;points.push(side(t,-4-(tail-4)*(1-t/headT)**2));}
 return 'M'+points.join(' L')+' Z';
}
function MarkerStrategyScreen({data,onClose,toolbar,artwork="/strategy/map-live-state.svg"}:{data:StrategyData;onClose:()=>void;toolbar?:(close:()=>void)=>ReactNode;artwork?:string}){
 const [ready,setReady]=useState(false);
 const artRef=useRef<HTMLImageElement>(null);
 const progress=useRef(0);
 // Cached images can finish before React attaches onLoad during hydration.
 useEffect(()=>{let cancelled=false;const image=artRef.current;const finish=()=>{if(!cancelled)setReady(true);};if(image?.complete)finish();else if(image){image.addEventListener('load',finish);image.addEventListener('error',finish);}
 return()=>{cancelled=true;image?.removeEventListener('load',finish);image?.removeEventListener('error',finish);};},[artwork]);
 const [p,setP]=useState(0),[closing,setClosing]=useState(false),[selected,setSelected]=useState(''),[decision,setDecision]=useState(data.focusDecisionId||'');const close=useRef(onClose);close.current=onClose;
 useEffect(()=>{if(!ready&&!closing)return;let frame=0,start:number|undefined;const initial=progress.current;const duration=matchMedia('(prefers-reduced-motion: reduce)').matches?1:closing?1100:3000;function tick(t:number){start??=t;const elapsed=t-start;const v=Math.min(1,Math.max(0,elapsed-(closing?0:300))/duration),ease=v*v*(3-2*v);const next=closing?initial*(1-ease):initial+(1-initial)*ease;progress.current=next;setP(next);if(v<1)frame=requestAnimationFrame(tick);else if(closing)close.current();}frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[closing,ready]);
 useEffect(()=>{const before=document.activeElement as HTMLElement;const old=document.body.style.overflow;document.body.style.overflow='hidden';const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setClosing(true);};addEventListener('keydown',key);return()=>{document.body.style.overflow=old;removeEventListener('keydown',key);before?.focus();};},[]);
 useEffect(()=>{setDecision(data.focusDecisionId||'');setSelected('');},[data.focusDecisionId]);
 const high=linkedObjects(data,decision);const army=data.armies.find(a=>a.id===selected),city=data.cities.find(a=>a.id===selected),action=data.actions.find(a=>a.id===selected),order=data.decisions.find(a=>a.id===(action?.decisionId||selected));const activeArmy=army||data.armies.find(a=>a.id===action?.armyId);const name=(id:string)=>data.cities.find(c=>c.id===id)?.name||data.armies.find(a=>a.id===id)?.name||id;
 const fields:Record<string,unknown>=army?{ID:army.id,名称:army.name,阵营:army.faction,统帅:army.commander,兵力:army.troops,'粮草(kg)':army.food,士气:army.morale,疲劳:army.fatigue,伤员:army.wounded,阵亡:army.dead,运输人员:army.transportPeople,位置:army.location||`${army.position.x}, ${army.position.y}`,状态:army.status}:city?{ID:city.id,名称:city.name,坐标:`${city.position.x}, ${city.position.y}`,控制方:city.controller,守将:city.governor,'库存粮草(kg)':city.food,防御:city.defense,驻军:city.garrison}:action?{ID:action.id,所属决策:order?.title,军队:activeArmy?.name,兵力:activeArmy?.troops,'粮草(kg)':activeArmy?.food,起点:name(action.from),目标:name(action.target),路线:action.route.map(p=>`${p.x},${p.y}`).join(' → '),进度:action.progress===undefined?undefined:`${action.progress}%`,时间:action.time,执行状态:action.status,具体决策:order?.command}:order?{ID:order.id,标题:order.title,命令内容:order.command,下达时间:order.time,执行状态:order.status,相关对象:order.objects.map(name).join('、')}:{};
 if(data.basisNote&&Object.keys(fields).length)fields['数据来源']=data.basisNote;
 const focusedDecision=data.decisions.find(d=>d.id===data.focusDecisionId);
 const cardArmy=data.armies.find(a=>focusedDecision?.objects.includes(a.id))||data.armies.find(a=>a.id==='army-wei-yan')||data.armies[0];
 const cardDecision=focusedDecision||data.decisions.find(d=>d.objects.includes(cardArmy?.id||''));
 const cardChanges=data.changes.filter(c=>c.entityId===cardArmy?.id);
 const latestRevision=Math.max(0,...cardChanges.map(c=>c.revision||0));
 const cardValue=(field:string,value:number|undefined)=>{const c=cardChanges.filter(c=>c.revision===latestRevision&&c.field===field).at(-1);return c?`${c.before.replace(/[,，]| kg| 人/g,'')} → ${c.after.replace(/[,，]| kg| 人/g,'')}`:value===undefined?'—':Math.round(value).toString();};
 const cardSummary=cardChanges.filter(c=>c.revision===latestRevision).at(-1)?.summary||cardDecision?.command||(cardArmy?'军队尚未出发，等待下达决策。':'等待该议题的世界状态数据。');
 const cardLines=Array.from(cardSummary.replace(/\s+/g,' ')).slice(0,36).join('').match(/.{1,18}/g)||[];
 const cardTime=data.worldTime.startYear?`公元${data.worldTime.startYear}年 · 第${Math.floor(data.worldTime.elapsedDays)+1}日`:'时间待提供';
 const anchor=army?.position||city?.position||(action?{x:(action.route[0].x+action.route[action.route.length-1].x)/2,y:(action.route[0].y+action.route[action.route.length-1].y)/2}:{x:420,y:370});
 const popupLeft=anchor.x>1150?anchor.x/1725*100-29:anchor.x/1725*100+2;
 const popupTop=Math.max(3,Math.min(48,(anchor.y-40)/863*100-5));
 const history=data.changes.filter(c=>selected&&((army||city)&&data.ready?c.entityId===selected:(c.objects.includes(selected)||c.decisionId===(action?.decisionId||selected))));
 return <div className={toolbar?"strategy-overlay strategy-gallery-overlay":"strategy-overlay"} role="dialog" aria-modal="true" aria-label="议题战略地图" onKeyDown={e=>{if(e.key!=='Tab')return;const nodes=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),[tabindex="0"]'));const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}>{toolbar?toolbar(()=>setClosing(true)):<button className="strategy-close-original" onClick={()=>setClosing(true)} aria-label="确认并收卷">×</button>}<div className="strategy-scroll"><div className="strategy-paper" style={{clipPath:`inset(0 ${(1-p)*50}%)`,pointerEvents:p===1?'auto':'none'}}><img ref={artRef} className="strategy-art" src={artwork} onLoad={()=>setReady(true)} onError={()=>setReady(true)} alt="三国战略地图"/><button className="strategy-original-decision" aria-label="查看决策并高亮相关对象" onClick={()=>{const d=cardDecision;if(d){setDecision(d.id);setSelected(d.id);}}}/>
<svg className="strategy-objects" viewBox="0 0 1725 863">
<g style={{pointerEvents:'none',fontFamily:'Songti SC,serif',fill:'#30291c'}} aria-label="当前决策与资源">
<text x="128" y="274" fontSize="18">{(cardDecision?.title||'初始部署').slice(0,10)}</text>
<text x="300" y="273" fontSize="14">{cardTime}</text>
<text x="298" y="339" fontSize="12">粮草 {cardValue('粮草',cardArmy?.food)} kg</text>
<text x="298" y="385" fontSize="12">兵力 {cardValue('兵力',cardArmy?.troops)}</text>
<text x="298" y="404" fontSize="13">{data.cities.find(c=>c.id==='changan')?.controller==='蜀'?'长安已由我方控制':data.cities.find(c=>c.id==='changan')?.controller?'长安仍由敌方控制':'长安归属待接入'}</text>
{cardLines.map((line,i)=><text key={i} x="135" y={441+i*23} fontSize="15" fill="#fff4dd">{line}</text>)}
</g><g transform="translate(0 -40)">
{data.actions.filter(a=>!a.phase||['planned','active'].includes(a.phase)||selected===a.id||high.has(a.id)).map(a=><g key={a.id} role="button" tabIndex={0} aria-label={`行动：${name(a.from)}到${name(a.target)}`} onClick={()=>setSelected(a.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(a.id);}}} className={high.has(a.id)||selected===a.id?'lit':''}><defs><linearGradient id={'arrow-opacity-'+a.id} gradientUnits="userSpaceOnUse" x1={(data.cities.find(c=>c.id===a.from)?.position||a.route[0]).x} y1={(data.cities.find(c=>c.id===a.from)?.position||a.route[0]).y} x2={(data.cities.find(c=>c.id===a.target)?.position||a.route[a.route.length-1]).x} y2={(data.cities.find(c=>c.id===a.target)?.position||a.route[a.route.length-1]).y}><stop offset="0%" stopColor="white"/><stop offset="18%" stopColor="white"/><stop offset="48%" stopColor="white" stopOpacity=".18"/><stop offset="58%" stopColor="white" stopOpacity=".18"/><stop offset="85%" stopColor="white"/><stop offset="100%" stopColor="white"/></linearGradient><mask id={'arrow-fade-'+a.id} maskUnits="userSpaceOnUse" x="0" y="0" width="1725" height="941"><rect width="1725" height="941" fill={'url(#arrow-opacity-'+a.id+')'}/></mask></defs><path className="strategy-action-arrow" mask={'url(#arrow-fade-'+a.id+')'} d={arrowShape(data.cities.find(c=>c.id===a.from)?.position||a.route[0],data.cities.find(c=>c.id===a.target)?.position||a.route[a.route.length-1])} fill="#b52c1e" stroke="#f5dfb4" strokeWidth="2" strokeLinejoin="round"/></g>)}
{data.cities.map(c=><g key={c.id} role="button" tabIndex={0} aria-label={c.name} transform={`translate(${c.position.x},${c.position.y})`} className={high.has(c.id)?'lit':''} onClick={()=>setSelected(c.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(c.id);}}}><rect x="-30" y="-32" width="60" height="64" fill="transparent"/>{c.color&&<circle cx="26" cy="-20" r="7" fill={c.color} stroke="#f5e6c5" strokeWidth="2"/>}<g className="strategy-icon-light">{c.id==='changan'||c.id==='hanzhong'?<image href="/strategy/icon-9.png" x="-34" y="-35" width="68" height="68"/>:<g><defs><clipPath id={'city-silhouette-'+c.id}><path d="M-17 10 L-17 4 -12 2 -12 -3 -18 -5 -11 -8 -10 -13 -3 -15 0 -19 3 -15 10 -13 11 -8 18 -5 12 -3 12 2 17 4 17 10Z"/></clipPath></defs><g clipPath={'url(#city-silhouette-'+c.id+')'}><image href={artwork} x={-c.position.x} y={40-c.position.y} width="1725" height="863"/></g></g>}</g></g>)}
{data.armies.map(a=><g key={a.id} role="button" tabIndex={0} aria-label={a.name} transform={`translate(${a.position.x},${a.position.y})`} className={high.has(a.id)?'lit':''} onClick={()=>setSelected(a.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(a.id);}}}>{a.mapPosition&&<g style={{pointerEvents:'none'}}><line x1="12" y1="16" x2={a.mapPosition.x-a.position.x} y2={a.mapPosition.y-a.position.y} stroke={a.color||'#20573f'} strokeWidth="1.5" strokeDasharray="3 3"/><circle cx={a.mapPosition.x-a.position.x} cy={a.mapPosition.y-a.position.y} r="4" fill={a.color||'#20573f'} stroke="#fff2d5"/></g>}<rect x="-24" y="-54" width="76" height="76" fill="transparent"/><image href="/strategy/icon-5.png" x="-24" y="-54" width="76" height="76" style={{filter:a.faction==='魏'?'sepia(1) saturate(3) hue-rotate(320deg)':a.faction==='吴'?'sepia(1) saturate(2) hue-rotate(160deg)':undefined}}/><circle cx="12" cy="16" r="5" fill={a.color||'#20573f'} stroke="#f5e6c5"/>{data.ready&&<text x="14" y="35" textAnchor="middle" style={{fontFamily:'Songti SC,serif',fontSize:15,fill:'#302515',paintOrder:'stroke',stroke:'#edddba',strokeWidth:3,pointerEvents:'none'}}>{a.name}</text>}</g>)}
</g></svg>{selected&&<section className="strategy-details" style={{left:`${popupLeft}%`,top:`${popupTop}%`,right:'auto'}} role="region" aria-label="对象详情"><button aria-label="关闭详情" onClick={()=>setSelected('')}>×</button><h3>{army?'军队':city?'城池':action?'行动':'决策'}详情</h3><dl>{Object.entries(fields).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v===undefined||v===null||v===''?'待接入':String(v)}</dd></div>)}</dl><h4>状态变化历史</h4>{history.length?history.map((h,i)=><article key={i}><p>{h.time} · 决策 {h.decisionId}</p><p>对象：{h.objects.map(name).join('、')}</p><p>{h.before} → {h.after}</p><p>原因：{h.reason}</p></article>):<p>暂无变化记录</p>}</section>}</div>{['left','right'].map(side=><svg key={side} className={'strategy-roller '+side} style={{[side]:`${(1-p)*(50-75/1725*100)}%`,opacity:p===1?0:1}} viewBox={side==='left'?'0 0 75 863':'1650 0 75 863'} aria-hidden="true"><image href={artwork} width="1725" height="863"/></svg>)}</div></div>;
}

export default function StrategyScreen(props:{data:StrategyData;onClose:()=>void;toolbar?:(close:()=>void)=>ReactNode;artwork?:string}){return props.toolbar&&!props.data.ready?<StrategyArchiveScreen {...props}/>:<MarkerStrategyScreen {...props}/>;}
