import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,readFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import sharp from 'sharp';
import {Store} from '../dist/store.js';import {parseSpec,AgentError} from '../dist/contracts.js';import {settle,initialWorld} from '../dist/world.js';import {Worker} from '../dist/worker.js';import {prepare,OpenAIArt} from '../dist/provider.js';import {makeServer} from '../dist/server.js';import {EngineBridge} from '../dist/engine.js';
const fixture=JSON.parse(readFileSync(new URL('../examples/ziwu.json',import.meta.url)));const event=JSON.parse(readFileSync(new URL('../examples/settlement.json',import.meta.url)));const spec=parseSpec(fixture.spec);
function setup(t){const dir=mkdtempSync(join(tmpdir(),'shijing-agents-'));const store=new Store(dir);t.after(()=>{store.close();rmSync(dir,{recursive:true,force:true});});return store;}
const one={...spec,cast:[spec.cast[0]]};
async function portrait(){return sharp({create:{width:1024,height:1024,channels:4,background:'#00000000'}}).composite([{input:Buffer.from('<svg width="1024" height="1024"><rect x="280" y="100" width="464" height="924" fill="#ad8040"/></svg>')}]).png().toBuffer();}
const story=()=>sharp({create:{width:912,height:1616,channels:3,background:'#7d694a'}}).png().toBuffer();
const mock={plan:async()=>({prompt:'test fixture',summary:'测试场景',night:false,evidence:[]}),generate:async j=>j.kind==='portrait'?portrait():story(),review:async()=>({pass:true,reason:'mock assertion only'})};
test('world: applies only confirmed event, advances time, keeps caller snapshot immutable',()=>{const before=initialWorld(spec,fixture.cities);const after=settle(before,event,spec);assert.equal(after.metrics.grain,29400);assert.equal(after.day,2);assert.equal(before.metrics.grain,30000);assert.equal(after.cities['长安'],'魏');assert.throws(()=>settle(before,{...event,confirmed:false},spec));});
test('world: rejects entire update on overdraft, unknown metrics, duplicate entries, invalid cities and stale version',()=>{const w=initialWorld(spec,fixture.cities);for(const bad of [{deltas:[{metric:'grain',by:-40000}]},{deltas:[{metric:'missing',by:1}]},{deltas:[{metric:'grain',by:1},{metric:'grain',by:2}]},{cityChanges:[{city:'长安',from:'蜀',to:'魏'}]},{elapsedDays:-1},{expectedVersion:2}])assert.throws(()=>settle(w,{...event,...bad},spec));assert.equal(w.metrics.grain,30000);});
test('world: city ownership and time are explicit changes',()=>{const w=initialWorld(spec,fixture.cities);assert.equal(settle(w,{...event,cityChanges:[{city:'长安',from:'魏',to:'蜀'}]},spec).cities['长安'],'蜀');});
test('store: repeated event never double-spends; changed payload conflicts; rejected events enqueue nothing',t=>{const s=setup(t),r=s.create(spec,fixture.cities);const before=s.jobs(r.id).length;s.apply(r.id,event);s.apply(r.id,event);assert.equal(s.run(r.id).world.metrics.grain,29400);assert.equal(s.history(r.id).length,1);assert.equal(s.jobs(r.id).length,before+1);assert.throws(()=>s.apply(r.id,{...event,summary:'changed'}));assert.throws(()=>s.apply(r.id,{...event,id:'invalid',expectedVersion:1,deltas:[{metric:'grain',by:-999999}]}));assert.equal(s.jobs(r.id).length,before+1);});
test('store: tasks and world survive process store reopen; in-flight calls require manual retry',t=>{const s=setup(t),r=s.create(one,fixture.cities);s.apply(r.id,event);const j=s.jobs(r.id)[0];s.step(j,'generating','test interruption');const reopened=new Store(s.directory);reopened.recover();assert.equal(reopened.run(r.id).world.metrics.grain,29400);assert.equal(reopened.job(j.id).status,'interrupted');reopened.close();});
test('worker: saves actual PNG, exact storyboard ratio, trace; no repeat charge on completed queue',async t=>{const s=setup(t),r=s.create(one);let calls=0;const worker=new Worker(s,{...mock,generate:async j=>{calls++;return mock.generate(j);}});await Promise.all([worker.drain(),worker.drain()]);assert.equal(calls,2);for(const j of s.jobs(r.id)){assert.equal(j.status,'succeeded');assert.equal(j.trace.at(-1).step,'succeeded');assert.ok(readFileSync(s.asset(j.asset)).length>0);if(j.kind==='storyboard'){const m=await sharp(s.asset(j.asset)).metadata();assert.equal(m.width*801,m.height*452);}}await worker.drain();assert.equal(calls,2);});
test('worker: bounded QA repair, original identity retained, passing images only published',async t=>{const s=setup(t),r=s.create(one);let n=0;const worker=new Worker(s,{...mock,review:async j=>{assert.equal(j.subjectId,j.kind==='portrait'?one.cast[0].id:'opening');return {pass:j.kind==='storyboard'||++n===3,reason:'wrong prop'};}});await worker.drain();assert.equal(s.jobs(r.id)[0].attempts,3);assert.equal(s.jobs(r.id)[0].status,'succeeded');});
test('worker: network and credit errors never automatically repeat billable calls',async t=>{const s=setup(t),r=s.create(one);const worker=new Worker(s,{...mock,generate:async()=>{throw new AgentError('quota',429);}});await worker.drain();for(const j of s.jobs(r.id)){assert.equal(j.attempts,1);assert.equal(j.status,'failed');assert.equal(j.asset,undefined);}});
test('images: rejects fake opaque transparency and invalid aspect ratio',async()=>{const opaque=await sharp({create:{width:1024,height:1024,channels:3,background:'#ffffff'}}).png().toBuffer();await assert.rejects(prepare(opaque,'portrait'),/ALPHA/);await assert.rejects(prepare(opaque,'storyboard'),/比例/);});
test('provider: missing key is explicit, makes no network call',async()=>{const previous=process.env.OPENAI_API_KEY;delete process.env.OPENAI_API_KEY;try{await assert.rejects(new OpenAIArt().request('responses',{}),/API Key/);}finally{if(previous)process.env.OPENAI_API_KEY=previous;}});
test('HTTP: create/read/events/manifest and origin protection',async t=>{const s=setup(t);const worker=new Worker(s,mock);worker.stopping=true;const server=makeServer(s,worker);await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>{server.close(r);server.closeAllConnections();}));const url='http://127.0.0.1:'+server.address().port;const post=(p,b,origin)=>fetch(url+p,{method:'POST',headers:{'Content-Type':'application/json',...(origin?{Origin:origin}:{})},body:JSON.stringify(b)});const res=await post('/runs',{...fixture,reuseKey:'same-topic'});assert.equal(res.status,202);const r=await res.json();assert.equal(r.jobs.length,6);const reused=await(await post('/runs',{...fixture,reuseKey:'same-topic'})).json();assert.equal(reused.id,r.id);assert.equal(s.runs().length,1);assert.equal((await post(`/runs/${r.id}/events`,event)).status,202);const snapshot=await(await fetch(url+`/runs/${r.id}`)).json();assert.equal(snapshot.world.metrics.grain,29400);assert.equal((await post('/runs',fixture,'https://attacker.invalid')).status,403);assert.equal((await fetch(url+'/assets/bad.png')).status,400);});
test('engine: inquiry keeps numeric state; confirmed snapshot becomes one scene; command retry does not execute twice',async t=>{const s=setup(t),r=s.create(one,{}, {gameId:'g-test',state:{troops:10000,grain:30000},messages:[],turn:0});const bridge=new EngineBridge(s);let calls=0,turn=0;bridge.request=async(path,body)=>{if(body){calls++;if(body.act)turn++;return{};}return{gameId:'g-test',turn,state:{troops:10000,grain:30000-turn*600},chat:turn?[{id:'settled-1',kind:'result',text:'行军已结算'}]:[],spec:one};};await bridge.message(r.id,{commandId:'ask',text:'有何建议',act:false});assert.equal(s.run(r.id).world.version,0);const cmd={commandId:'act',text:'执行',act:true};await bridge.message(r.id,cmd);await bridge.message(r.id,cmd);assert.equal(calls,2);assert.equal(s.run(r.id).world.metrics.grain,29400);assert.equal(s.jobs(r.id).filter(j=>j.subjectId==='settled-1').length,1);});

test('engine: ambiguous network response never replays action with same command id',async t=>{const s=setup(t),r=s.create(one,{}, {gameId:'g-timeout',state:{troops:10000,grain:30000},messages:[],turn:0});const bridge=new EngineBridge(s);let calls=0;bridge.request=async()=>{calls++;throw new AgentError('timeout',502);};const cmd={commandId:'uncertain',text:'行军',act:true};await assert.rejects(bridge.message(r.id,cmd));await assert.rejects(bridge.message(r.id,cmd),/禁止自动重复执行/);assert.equal(calls,1);});

test('network: only confirmed destinations receive credentials; root endpoints normalize to v1',async()=>{const {openAIBase,systemProxy}=await import('../dist/network.js');assert.equal(openAIBase({}),'https://api.openai.com/v1');assert.throws(()=>openAIBase({OPENAI_BASE_URL:'https://service.example'}),/确认/);assert.equal(openAIBase({OPENAI_BASE_URL:'https://service.example/',OPENAI_COMPATIBLE_CONFIRMED:'true'}),'https://service.example/v1');assert.throws(()=>openAIBase({OPENAI_BASE_URL:'http://service.example',OPENAI_COMPATIBLE_CONFIRMED:'true'}),/HTTPS/);assert.throws(()=>openAIBase({OPENAI_BASE_URL:'https://user:secret@service.example',OPENAI_COMPATIBLE_CONFIRMED:'true'}));assert.equal(systemProxy('HTTPSEnable : 1\nHTTPSProxy : 127.0.0.1\nHTTPSPort : 7890'),'http://127.0.0.1:7890');assert.equal(systemProxy('HTTPSEnable : 0\nHTTPSProxy : 127.0.0.1\nHTTPSPort : 7890'),undefined);});

test('topic: fast draft preserves five distinct identities and defers research to background tasks',async()=>{const {createTopicPlan}=await import('../dist/topic.js');const original=globalThis.fetch;const key=process.env.OPENAI_API_KEY;const base=process.env.OPENAI_BASE_URL;process.env.OPENAI_API_KEY='test-only';process.env.OPENAI_BASE_URL='https://api.openai.com/v1';try{globalThis.fetch=async(_url,opts)=>{const body=JSON.parse(opts.body);assert.equal(body.tools,undefined);assert.equal(body.max_output_tokens,2200);const result={characters:Array.from({length:5},(_,i)=>({name:'人物'+i,role:'将领',personality:'审慎',opening:'讨论方案',appearance:'时代化演绎'})),factNote:'选角初稿，绘图前核对史据'};return Response.json({output:[{content:[{type:'output_text',text:JSON.stringify(result)}]}]});};const p=await createTopicPlan({topic:{title:'测试议题',description:'仅讨论',year:228,season:'春',faction:'shu'}});assert.equal(p.characters.length,5);assert.equal(new Set(p.characters.map(c=>c.id)).size,5);assert.equal(p.characters[0].source,'');}finally{globalThis.fetch=original;if(key===undefined)delete process.env.OPENAI_API_KEY;else process.env.OPENAI_API_KEY=key;if(base===undefined)delete process.env.OPENAI_BASE_URL;else process.env.OPENAI_BASE_URL=base;}});


test('provider: research retains search and schema without unsupported max_tool_calls',async()=>{const art=new OpenAIArt();let request;art.request=async(path,body)=>{request=body;return{output:[{content:[{type:'output_text',text:'{"ok":true}'}]}]};};assert.deepEqual(await art.structured('check','Rules','Input',{type:'object'},true,2200),{ok:true});assert.deepEqual(request.tools,[{type:'web_search'}]);assert.equal(request.max_tool_calls,undefined);assert.equal(request.text.format.type,'json_schema');});

test('provider: rejects alternate image model before any paid request',async()=>{const old=process.env.OPENAI_IMAGE_MODEL;try{process.env.OPENAI_IMAGE_MODEL='gpt-image-2-vip';const art=new OpenAIArt();art.request=async()=>{assert.fail('must not call provider');};await assert.rejects(art.generate({kind:'storyboard',feedback:'',plan:{prompt:'test',summary:'test',night:false,evidence:[]}}),/生图已限定/);}finally{if(old===undefined)delete process.env.OPENAI_IMAGE_MODEL;else process.env.OPENAI_IMAGE_MODEL=old;}});

test('skills: required references are actually loaded',async()=>{const {loadSkill,characterReferences}=await import('../dist/skill-runtime.js');const text=loadSkill('portrait');for(const name of characterReferences)assert.ok(text.includes(`references/${name}.md`));assert.ok(loadSkill('storyboard').includes('references/context-routing.md'));});
test('calibration: a failed first portrait blocks the other portraits, independent story can finish',async t=>{const s=setup(t),r=s.create({...one,cast:spec.cast.slice(0,2)});const w=new Worker(s,{...mock,generate:async j=>{if(j.kind==='portrait')throw new AgentError('network failure',502);return story();}});await w.drain();const jobs=s.jobs(r.id);assert.equal(jobs[0].status,'failed');assert.equal(jobs[1].status,'queued');assert.equal(jobs[1].attempts,0);assert.equal(jobs[2].status,'succeeded');});
test('calibration: native alpha failure persists chroma for this and all remaining characters',async t=>{const s=setup(t),r=s.create({...one,cast:spec.cast.slice(0,2)});let first=true;const paths=[];const w=new Worker(s,{...mock,generate:async j=>{if(j.kind==='portrait'){paths.push(j.transparency);if(first){first=false;throw new AgentError('[ALPHA] no alpha',422);}}return mock.generate(j);}});await w.drain();assert.deepEqual(paths,['native','chroma','chroma']);assert.equal(s.jobs(r.id)[1].transparency,'chroma');assert.ok(readFileSync(join(s.directory,'qa',s.jobs(r.id)[0].id,'attempt-2','draft.png')).length>0);});
test('original scripts: generated chroma fixture is converted, aligned, validated, and previews saved',async t=>{const {prepareCharacter}=await import('../dist/skill-runtime.js');const s=setup(t);const draft=await sharp({create:{width:1024,height:1024,channels:3,background:'#ff00ff'}}).composite([{input:Buffer.from('<svg width="1024" height="1024"><rect x="280" y="100" width="464" height="924" fill="#ad8040"/></svg>')}]).png().toBuffer();const dir=join(s.directory,'script-check');const output=await prepareCharacter({transparency:'chroma'},draft,dir);assert.equal((await sharp(output).metadata()).hasAlpha,true);for(const n of ['chroma_to_alpha.py.log','align_bottom_crop.py.log','validate_character_assets.py.log','preview-black.png','preview-white.png'])assert.ok(readFileSync(join(dir,n)).length>0);});
test('design: empty prop/action plans cannot proceed to images',async()=>{const {validateDesign}=await import('../dist/art-design.js');assert.throws(()=>validateDesign({}),/候选/);assert.throws(()=>validateDesign({candidates:['one','two'],propCard:{}}),/Prop Card/);});
test('resume: review outage reuses saved draft without another paid image request',async t=>{const s=setup(t),r=s.create(one);let images=0,down=true;const w=new Worker(s,{...mock,generate:async j=>{images++;return mock.generate(j);},review:async j=>{if(j.kind==='portrait'&&down)throw new AgentError('review timeout',502);return {pass:true,reason:'mock'};}});await w.drain();const j=s.jobs(r.id)[0];assert.equal(j.resumeDraft,true);assert.ok(readFileSync(s.draftPath(j)).length>0);const before=images;down=false;s.retry(j.id);await w.drain();assert.equal(images,before);assert.equal(s.job(j.id).status,'succeeded');});
test('shutdown: stop during plan never starts a paid image request',async t=>{const s=setup(t);s.create(one);let images=0;const w=new Worker(s,{...mock,plan:async j=>{w.stopping=true;return mock.plan(j);},generate:async j=>{images++;return mock.generate(j);}});await w.drain();assert.equal(images,0);assert.equal(s.jobs()[0].status,'interrupted');});
test('image2: every portrait request uses opaque chroma, never unsupported transparent',async()=>{const art=new OpenAIArt();let body;art.request=async(path,b)=>{body=b;return {data:[{b64_json:Buffer.from('test-only-png-placeholder').toString('base64')}]};};await art.generate({kind:'portrait',feedback:'',plan:{prompt:'fixture',summary:'fixture',night:false,evidence:[]}});assert.equal(body.get('model'),'gpt-image-2');assert.equal(body.get('background'),'opaque');assert.ok(body.get('prompt').includes('#FF00FF'));assert.equal(art.transparencyMode,'chroma');});
