import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {Store} from '../dist/store.js';
import {WorldAgent} from '../dist/world-agent.js';
import {buildInitialWorld} from '../dist/world-bootstrap.js';
import {advanceWorld,issueOrder} from '../dist/simulation-engine.js';
import {validateWorld} from '../dist/world-state.js';
import {foodTotal,peopleTotal} from '../dist/simulation-state.js';
import {parseLocalCommand} from '../dist/simulation-commands.js';
import {makeServer} from '../dist/server.js';
const spec={id:'northern-test',title:'诸葛亮北伐：子午谷奇谋',scenario:{background:'公元228年春。汉中向长安进军。'},cast:[{id:'wei-yan',name:'魏延',role:'蜀汉将领',description:'测试'}],metrics:[]};
function setup(t){const dir=mkdtempSync(fileURLToPath(new URL('./.runtime/run-',import.meta.url)));const store=new Store(dir),agent=new WorldAgent(store),run=store.create(spec);t.after(()=>{store.close();rmSync(dir,{recursive:true,force:true});});return{store,agent,id:run.id,dir};}
function fixture(){return buildInitialWorld({id:'fixture',spec,mode:'standalone',world:{version:0,day:0,metrics:{},cities:{}},engineTurn:0}).snapshot;}
const order=(w,kind='march',extra={})=>({commandId:'order-'+w.revision,expectedRevision:w.revision,armyId:'army-wei-yan',kind,...(kind==='garrison'?{}:{targetCityId:'changan'}),...extra});
const advance=(w,hours=24)=>({commandId:'advance-'+w.revision,expectedRevision:w.revision,hours});
function balance(w){const s=w.simulation;assert.ok(Math.abs(foodTotal(w,s)+s.ledger.consumedKg+s.ledger.spoiledKg-s.ledger.initialFoodKg)<.001);assert.equal(peopleTotal(w,s),s.ledger.initialPeople);validateWorld(w);}
function atChangan(w){const a=w.armies['army-wei-yan'],m=w.simulation.armies[a.id];m.atCityId='changan';m.roadId=null;a.location={kind:'field',point:w.cities.changan.point,label:'长安城外'};a.status='resting';return w;}
test('new northern run has initialized armies, source and no invented decisions',t=>{const {agent,id}=setup(t),w=agent.getWorld(id);assert.ok(w.simulation);assert.equal(w.armies['army-wei-yan'].foodKg,60000);assert.equal(Object.keys(w.actions).length,0);assert.equal(agent.listEvents(id).length,0);assert.match(agent.basis(id).note,/模拟/);balance(w);});
test('ineligible scenarios and externally owned worlds are not auto-filled',()=>{for(const patch of [{mode:'engine'},{spec:{...spec,title:'赤壁',scenario:{background:'公元208年秋'}}},{world:{version:1,day:0,metrics:{},cities:{}}}])assert.equal(buildInitialWorld({id:'fixture',spec,mode:'standalone',world:{version:0,day:0,metrics:{},cities:{}},engineTurn:0,...patch}),null);});
test('order does not advance time; movement consumes food and accrues fatigue without inventing casualties',()=>{let w=fixture();w=issueOrder(w,order(w)).world;assert.equal(w.clock.elapsedDays,0);const result=advanceWorld(w,advance(w));w=result.world;assert.equal(w.armies['army-wei-yan'].foodKg,54000);assert.equal(w.armies['army-wei-yan'].troops,5000);assert.ok(Math.abs(w.simulation.armies['army-wei-yan'].fatigue-28)<1e-6);assert.ok(w.simulation.armies['army-wei-yan'].roadKm>12&&w.simulation.armies['army-wei-yan'].roadKm<14);assert.equal(w.clock.elapsedDays,1);balance(w);});
test('arrival pauses at actual subday time and does not capture a defended city',()=>{let w=fixture();w.simulation.roads['road-ziwu'].distanceKm=3;w=issueOrder(w,order(w,'attack')).world;const r=advanceWorld(w,advance(w));assert.ok(r.report.advancedHours<24);assert.equal(r.world.cities.changan.ownerFactionId,'wei');assert.equal(r.world.armies['army-wei-yan'].troops,5000);assert.equal(r.world.simulation.armies['army-wei-yan'].atCityId,'changan');balance(r.world);});
test('simultaneous battle, deterministic replay, no dictionary iteration advantage',()=>{let w=atChangan(fixture());w=issueOrder(w,order(w,'attack')).world;const r=advanceWorld(w,advance(w,6));assert.ok(r.world.armies['army-wei-yan'].troops<5000);assert.ok(r.world.armies['army-changan'].troops<3000);assert.deepEqual(advanceWorld(w,advance(w,6)),r);const reversed=structuredClone(w);reversed.armies=Object.fromEntries(Object.entries(reversed.armies).reverse());reversed.simulation.activeArmyIds.reverse();const second=advanceWorld(reversed,advance(reversed,6));for(const id of w.simulation.activeArmyIds)assert.deepEqual(second.world.armies[id],r.world.armies[id]);balance(r.world);});
test('rest restores fatigue and wounded personnel without creating people',()=>{let w=fixture(),a=w.armies['army-wei-yan'],m=w.simulation.armies[a.id];a.troops-=100;m.wounded=100;m.fatigue=60;w=issueOrder(w,order(w,'garrison')).world;const r=advanceWorld(w,advance(w));assert.ok(r.world.simulation.armies[a.id].wounded<100);assert.ok(r.world.simulation.armies[a.id].fatigue<60);balance(r.world);});
test('hunger and zero water pause; closed road cannot be overridden by multiplier',()=>{let w=fixture();w=issueOrder(w,order(w)).world;const a=w.armies['army-wei-yan'];w.simulation.ledger.consumedKg+=a.foodKg;a.foodKg=0;const r=advanceWorld(w,advance(w));assert.match(r.report.pauseReason,/补给/);assert.ok(r.report.advancedHours<=1);balance(r.world);const closed=fixture();closed.simulation.roads['road-ziwu'].open=false;assert.throws(()=>issueOrder(closed,order(closed,'march',{effects:[{id:'route-familiarity',factor:1.05,roadId:'road-ziwu',durationHours:24,reason:'熟悉路线'}]})),/通行/);});
test('effects have bounds, eligibility, expiry and cannot stack; raw numeric patches reject',()=>{let w=fixture();const e={id:'route-familiarity',factor:1.05,roadId:'road-ziwu',durationHours:1,reason:'熟悉路线'};assert.throws(()=>issueOrder(w,order(w,'march',{effects:[{...e,factor:2}]})),/上限/);assert.throws(()=>issueOrder(w,{...order(w),troops:9999}),/不允许/);w=issueOrder(w,order(w,'march',{effects:[e]})).world;assert.throws(()=>issueOrder(w,order(w,'march',{effects:[e]})),/重复/);w=advanceWorld(w,advance(w,2)).world;assert.equal(w.simulation.armies['army-wei-yan'].effects.length,0);balance(w);});
test('resource transfers reject overdraft and in-transit transport never teleports food',()=>{let w=fixture();assert.throws(()=>issueOrder(w,order(w,'resupply',{targetCityId:undefined,sourceCityId:'hanzhong',foodKg:1000000})),/库存/);w.simulation.roads['road-ziwu'].distanceKm=12;w=issueOrder(w,order(w)).world;w=advanceWorld(w,advance(w,4)).world;const before=w.armies['army-wei-yan'].foodKg;w=issueOrder(w,order(w,'resupply',{targetCityId:undefined,sourceCityId:'hanzhong',foodKg:1000})).world;assert.equal(w.armies['army-wei-yan'].foodKg,before);assert.equal(Object.values(w.simulation.shipments)[0].status,'travelling');balance(w);});
test('capture occurs only after defenders surrender and occupying army enters',()=>{let w=atChangan(fixture());w.armies['army-changan'].morale=5;w=issueOrder(w,order(w,'attack')).world;const r=advanceWorld(w,advance(w,1));assert.equal(r.world.cities.changan.ownerFactionId,'shu');assert.equal(r.world.armies['army-wei-yan'].location.kind,'city');assert.equal(r.world.simulation.armies['army-changan'].captured,3300);assert.equal(r.world.cities.changan.foodKg,50000);balance(r.world);});
test('full replay survives database restart, stale writes, duplicate requests and raw settlement rejection',t=>{const {agent,id,dir}=setup(t);const first=order(agent.getWorld(id));agent.localOrder(id,first);const input=advance(agent.getWorld(id));agent.localAdvance(id,input);const state=agent.getWorld(id);assert.equal(agent.localAdvance(id,input).alreadyApplied,true);assert.deepEqual(agent.getWorld(id),state);assert.throws(()=>agent.localAdvance(id,{...input,commandId:'stale'}),/版本/);assert.throws(()=>agent.localAdvance(id,{...input,hours:12}),/不同内容/);const second=new Store(dir);try{const other=new WorldAgent(second);assert.deepEqual(other.getWorld(id),state);assert.equal(other.localOrder(id,first).alreadyApplied,true);}finally{second.close();}assert.throws(()=>agent.applySettlement(id,{settlementId:'patch',expectedRevision:state.revision,decisionId:null,source:'referee',elapsedDays:1,title:'x',summary:'x',mutations:[]}),/禁止/);balance(state);});
test('strict command parser never interprets questions or negations as orders',()=>{const w=fixture();for(const text of ['不要魏延进攻长安','魏延如果进攻长安','魏延进攻长安吗','魏延进攻长安，然后增加兵力'])assert.throws(()=>parseLocalCommand(w,text,'cmd'));assert.equal(parseLocalCommand(w,'魏延 进攻 长安','cmd').input.kind,'attack');assert.equal(parseLocalCommand(w,'推进 2 天','cmd').input.hours,48);});
test('HTTP local commands, reads and messages do not invoke a worker or external API',async t=>{const {agent,store,id}=setup(t);let calls=0;const server=makeServer(store,{active:false,drain(){calls++;}});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>{server.close(r);server.closeAllConnections();}));const base='http://127.0.0.1:'+server.address().port;const post=(path,data)=>fetch(base+'/runs/'+id+'/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const jobs=store.jobs(id).length;let res=await post('messages',{commandId:'msg1',text:'魏延 行军 长安',act:true});assert.equal(res.status,202,await res.clone().text());res=await post('messages',{commandId:'msg2',text:'推进 1 天',act:true});assert.equal(res.status,202,await res.clone().text());const v=await res.json();assert.equal(v.strategy.ready,true);assert.equal(v.strategy.armies.find(a=>a.id==='army-wei-yan').food,54000);const rev=agent.getWorld(id).revision;await fetch(base+'/runs/'+id);assert.equal(agent.getWorld(id).revision,rev);assert.equal(store.jobs(id).length,jobs);assert.equal(calls,0);});
test('no water means no movement; time and consumption still settle without NaN',()=>{let w=fixture();w.simulation.roads['road-ziwu'].waterAccessible=false;w.simulation.armies['army-wei-yan'].waterLitres=0;w=issueOrder(w,order(w)).world;const r=advanceWorld(w,advance(w));assert.equal(r.world.simulation.armies['army-wei-yan'].roadKm,0);assert.match(r.report.pauseReason,/供水/);balance(r.world);});
test('forced march pauses at its fatigue threshold and retreat creates a new reverse route',()=>{let w=fixture();w.simulation.armies['army-wei-yan'].fatigue=69;w=issueOrder(w,order(w,'forced-march')).world;let r=advanceWorld(w,advance(w));w=r.world;assert.match(r.report.pauseReason,/疲劳/);assert.ok(r.report.advancedHours<2);const previous=w.simulation.armies['army-wei-yan'].roadKm;w=issueOrder(w,order(w,'retreat',{targetCityId:'hanzhong'})).world;w=advanceWorld(w,advance(w)).world;assert.ok(w.simulation.armies['army-wei-yan'].atCityId==='hanzhong'||w.simulation.armies['army-wei-yan'].roadKm<previous);balance(w);});
test('transport delivers to a waiting army and returns personnel with food conserved',()=>{let w=fixture();w.simulation.roads['road-ziwu'].distanceKm=6;w=issueOrder(w,order(w)).world;w=advanceWorld(w,advance(w,3)).world;const a=w.armies['army-wei-yan'],m=w.simulation.armies[a.id];w=issueOrder(w,order(w,'resupply',{targetCityId:undefined,sourceCityId:'hanzhong',foodKg:1000})).world;
 // Independent fixture holds at the agreed rendezvous, without moving or creating resources.
 const mm=w.simulation.armies[a.id],oo=mm.order;w.actions[oo.actionId].status='failed';w.actions[oo.actionId].endedDay=w.clock.elapsedDays;w.decisions[oo.id].status='failed';oo.status='failed';a.location=w.armies[a.id].location={kind:'field',point:w.cities.hanzhong.point,label:'补给会合点'};w.armies[a.id].status='resting';
 let delivered=false;for(let i=0;i<12;i++){const r=advanceWorld(w,advance(w,2));w=r.world;delivered ||= r.report.pauseReason==='补给抵达';balance(w);if(Object.values(w.simulation.shipments)[0].status==='returned')break;}
 assert.equal(delivered,true);assert.equal(Object.values(w.simulation.shipments)[0].status,'returned');assert.equal(w.simulation.cities.hanzhong.transportAvailable,800);
});
test('long siege and starvation remain valid through repeat pauses and terminal armies',()=>{let w=atChangan(fixture());w=issueOrder(w,order(w,'besiege')).world;let captured=false;for(let i=0;i<100;i++){const r=advanceWorld(w,advance(w,24));w=r.world;balance(w);if(w.cities.changan.ownerFactionId==='shu'){captured=true;break;}}assert.equal(captured,true);});
test('startup migrates only untouched old presets and never replaces an advanced world',t=>{const {store,agent,id}=setup(t);let w=agent.getWorld(id);delete w.simulation;w.armies['army-wei-yan'].foodKg=5000;store.db.prepare('UPDATE world_states SET init_id=?,payload=? WHERE run_id=?').run('northern-expedition-preset-v1',JSON.stringify(w),id);assert.equal(agent.bootstrapPendingRuns(),1);assert.ok(agent.getWorld(id).simulation);agent.localOrder(id,order(agent.getWorld(id)));const before=agent.getWorld(id);assert.equal(agent.bootstrapPendingRuns(),0);assert.deepEqual(agent.getWorld(id),before);});
test('role observations exclude unknown enemy resources and orders',t=>{const {agent,id}=setup(t);const o=agent.localObservation(id);assert.equal(o.armies.length,1);assert.equal(o.intelligence.length,0);assert.ok(!o.cities.some(c=>c.id==='changan'));assert.ok(!JSON.stringify(o).includes('army-changan'));});
test('reinforcement uses observed threat and leaves another home defender in place',()=>{let w=fixture(),s=w.simulation;
 const support=w.armies['army-luoyang'],home=w.armies['army-bingzhou'];home.location={kind:'city',cityId:'luoyang'};s.armies[home.id].atCityId='luoyang';s.activeArmyIds.push(support.id,home.id);
 s.roads['road-relief']={...s.roads['road-ziwu'],id:'road-relief',from:'luoyang',to:'changan',distanceKm:6};
 s.intelligence.push({observerFactionId:'wei',enemyArmyId:'army-wei-yan',seenHour:0,atCityId:'changan',roadId:null,roadKm:0,estimatedTroops:5000});
 const r=advanceWorld(w,advance(w,1));const pair=[support.id,home.id].map(id=>r.world.simulation.armies[id]);assert.equal(pair.filter(m=>m.order.kind==='march').length,1);assert.equal(pair.filter(m=>m.atCityId==='luoyang').length,1);balance(r.world);
});
test('malformed simulation input rejects before committing; reserve counting is bounded in multi-contact combat',()=>{const bad=fixture();bad.simulation.armies=null;assert.throws(()=>validateWorld(bad),/缺少/);let w=atChangan(fixture());const extra=w.armies['army-luoyang'];extra.location={kind:'city',cityId:'changan'};w.simulation.armies[extra.id].atCityId='changan';w.simulation.activeArmyIds.push(extra.id);w=issueOrder(w,order(w,'attack')).world;const r=advanceWorld(w,advance(w,1));const traces=r.report.traces.filter(t=>t.rule==='combat'&&t.entityId.includes('army-wei-yan'));let sum=0;for(const t of traces)sum+=t.entityId.startsWith('army-wei-yan')?t.inputs.aEngaged:t.inputs.bEngaged;assert.ok(sum<=2500);balance(r.world);});
