/**
 * 预置史实快照（docs/07 §4「内置百科快照」）：常见考题的无网可溯源数据。
 * 条目出自《三国志》《宋史》《旧唐书》等公开史书原文/通说；
 * 来源标 'rag'（内部索引层），估算项显式 estimated=true + basis。
 */
import type { Fact } from '@sim/contracts';

export type PresetFact = Omit<Fact, 'id'>;

/** 北伐 · 三国（第一批考点） */
const THREE_KINGDOMS: PresetFact[] = [
  {
    claim: '建兴五年（227年），诸葛亮率诸军北驻汉中，出师北伐关中。',
    entity: '诸葛亮',
    source: 'rag',
    estimated: false,
    confidence: 0.95,
    url: '《三国志·诸葛亮传》',
    basis: '逗号出处',
    tags: ['三国', '北伐', '诸葛亮', '汉中'],
  },
  {
    claim: '建兴六年（228）春第一次北伐出祁山，马谡失街亭，诸葛亮退兵。',
    entity: '北伐',
    source: 'rag',
    estimated: false,
    confidence: 0.95,
    url: '《三国志·诸葛亮传》',
    basis: '逗号出处',
    tags: ['三国', '诸葛亮', '街亭', '马谡'],
  },
  {
    claim: '魏延尝献计，愿领精兵五千由子午谷奇袭长安，诸葛亮未许。',
    entity: '魏延',
    source: 'rag',
    estimated: false,
    confidence: 0.9,
    url: '《三国志·魏延传》裴松之注引《魏略》',
    tags: ['魏延', '子午谷', '奇谋', '诸葛亮'],
  },
  {
    claim: '魏延官至前将军征西大将军，假节，封南郑侯。',
    entity: '魏延',
    source: 'rag',
    estimated: false,
    confidence: 0.9,
    url: '《三国志·魏延传》',
    tags: ['魏延', '官职', '蜀汉'],
  },
  {
    claim: '杨仪为丞相府长史，后迁尚书令，与魏延交恶。',
    entity: '杨仪',
    source: 'rag',
    estimated: false,
    confidence: 0.85,
    url: '《三国志·杨仪传》',
    tags: ['杨仪', '蜀汉'],
  },
  {
    claim: '姜维为凉州天水郡人，降蜀后深得诸葛亮器重，亮卒后总领其军。',
    entity: '姜维',
    source: 'rag',
    estimated: false,
    confidence: 0.85,
    url: '《三国志·姜维传》',
    tags: ['姜维', '天水', '诸葛'],
  },
  {
    claim: '费祎为诸葛亮所重，拜中护军、司马，后任尚书令秉政。',
    entity: '费祎',
    source: 'rag',
    estimated: false,
    confidence: 0.85,
    url: '《三国志·费祎传》',
    tags: ['费祎', '尚书令', '蜀汉'],
  },
  {
    claim: '建兴十二年（234），诸葛亮卒于五丈原军中，年五十四。',
    entity: '诸葛亮',
    source: 'rag',
    estimated: false,
    confidence: 0.95,
    url: '《三国志·诸葛亮传》',
    tags: ['诸葛亮', '五丈原', '234'],
  },
  {
    claim: '建兴十二年（234），魏军司马懿坚壁渭南拒守，不与诸葛亮交战，相持百余日。',
    entity: '司马懿',
    source: 'rag',
    estimated: false,
    confidence: 0.85,
    url: '《晋书·宣帝纪》',
    basis: '通说',
    tags: ['司马懿', '渭南', '诸葛亮', '三国'],
  },
  {
    claim: '蜀汉人口不足魏国四分之一，军队后勤多依赖汉中屯田。',
    entity: '北伐',
    source: 'rag',
    estimated: true,
    confidence: 0.6,
    basis: '史书户口对比（蜀约九十万口、魏约四百四十万口）的区间估算',
    tags: ['军粮', '屯田', '经济'],
  },
  {
    claim: '两线作战需要兵力达到对手单线的1.5倍以上才可能成功，蜀汉巅峰兵力约10万，远不足以同时攻魏吴。',
    entity: '军事',
    source: 'rag',
    estimated: true,
    confidence: 0.55,
    basis: '按三国各势力兵力规模与古代战争后勤规律推导',
    tags: ['两线作战', '兵力', '军事', '蜀汉', '曹魏', '东吴'],
  },
  {
    claim: '诸葛亮北伐最多同时对付一个方向，从未敢两线开战，以国力悬殊为根本原因。',
    entity: '诸葛亮',
    source: 'rag',
    estimated: false,
    confidence: 0.9,
    url: '《三国志·诸葛亮传》通说',
    tags: ['诸葛亮', '北伐', '两线作战', '蜀汉', '军事'],
  },
  {
    claim: '孙吴兵力约20-30万，主要守江淮和荆州；曹魏鼎盛期兵力约60-80万，分散在各大军区。',
    entity: '曹魏',
    source: 'rag',
    estimated: true,
    confidence: 0.6,
    basis: '《晋书·兵志》《资治通鉴》诸传记述的区间估算',
    tags: ['曹魏', '东吴', '兵力', '军事', '三国'],
  },
  {
    claim: '子午谷道自沔县通长安路三百余里，栈道险峻，行军困难。',
    entity: '子午谷',
    source: 'rag',
    estimated: true,
    confidence: 0.6,
    basis: '按《水经注》所述绛帐 - 子午道里程与地势的估算',
    tags: ['子午谷', '地理', '行军'],
  },
];

/** 王安石变法（宋） */
const WANG_ANSHI: PresetFact[] = [
  {
    claim: '熙宁二年（1069），王安石拜参知政事，主持变法，史称熙宁新法。',
    entity: '王安石',
    source: 'rag',
    estimated: false,
    confidence: 0.9,
    url: '《宋史·王安石传》',
    tags: ['王安石', '变法', '宋神宗'],
  },
  {
    claim: '新法包括青苗法、免役法、农田水利法、保甲法等。',
    entity: '青苗法',
    source: 'rag',
    estimated: false,
    confidence: 0.9,
    url: '《宋史·食货志》',
    tags: ['王安石', '变法', '青苗'],
  },
  {
    claim: '青苗法由官府于春赋时贷钱粮给农民，秋收加息归还。',
    entity: '青苗法',
    source: 'rag',
    estimated: false,
    confidence: 0.85,
    url: '《宋史·食货志》',
    tags: ['青苗', '官府', '经济'],
  },
  {
    claim: '司马光等旧党持续反对新法，新旧党争贯穿整个政治时期。',
    entity: '司马光',
    source: 'rag',
    estimated: false,
    confidence: 0.85,
    url: '《宋史·司马光传》',
    tags: ['司马光', '旧党', '党争'],
  },
  {
    claim: '元丰八年（1085）神宗薨，新法被废，此后熙丰绍之间反复起落。',
    entity: '新法',
    source: 'rag',
    estimated: true,
    confidence: 0.7,
    basis: '按《宋史》诸传中绍圣改法过程的归纳',
    url: '《宋史·食货志》',
    tags: ['新法', '哲宗', '党争'],
  },
];

/** 安史之乱（唐） */
const ANSHI: PresetFact[] = [
  {
    claim: '天宝十四载（755），范阳（兼卢龙）节度使安禄山起兵叛唐，安史之乱爆发。',
    entity: '安史之乱',
    source: 'rag',
    estimated: false,
    confidence: 0.9,
    url: '《旧唐书·玄宗纪》',
    tags: ['安禄山', '范阳', '叛乱'],
  },
  {
    claim: '玄宗宠信藩镇，范阳兼辖三镇兵权，遂成安禄山拥兵自重之基。',
    entity: '节度使',
    source: 'rag',
    estimated: false,
    confidence: 0.85,
    url: '《新唐书·兵志》',
    tags: ['安禄山', '藩镇', '安史之乱'],
  },
  {
    claim: '天宝十五载（756），玄宗奔蜀，行至马嵬驿，禁军杀杨国忠、杨贵妃。',
    entity: '马嵬坡',
    source: 'rag',
    estimated: false,
    confidence: 0.9,
    url: '《旧唐书·玄宗纪》',
    tags: ['马嵬', '杨国忠', '杨贵妃', '安史之乱'],
  },
  {
    claim: '郭子仪、李光弼率兵平叛，广德元年（763）史朝义自缢，乱平。',
    entity: '郭子仪',
    source: 'rag',
    estimated: false,
    confidence: 0.9,
    url: '《旧唐书·郭子仪传》',
    tags: ['郭子仪', '李光弼', '平定', '安史之乱'],
  },
  {
    claim: '安史乱后河北藩镇割据延续近二百年，唐由盛转衰。',
    entity: '藩镇',
    source: 'rag',
    estimated: true,
    confidence: 0.75,
    basis: '按《旧唐书·藩镇饰序》对割据时限的总体判断',
    url: '《旧唐书·藩镇篇》',
    tags: ['藩镇', '安史之乱'],
  },
];

/** 崇祯 · 明末（验收关键词） */
const CHONGZHEN: PresetFact[] = [
  {
    claim: '崇祯十七年（1644）三月，李自成破燕京，崇祯帝自缢于景山（煤山）。',
    entity: '崇祯帝',
    source: 'rag',
    estimated: false,
    confidence: 0.95,
    url: '《明史·庄烈帝纪》',
    tags: ['崇祯', '李自成', '甲申'],
  },
  {
    claim: '崇祯元年（1628）即位，随即清算魏忠贤阉党，定逆案。',
    entity: '崇祯帝',
    source: 'rag',
    estimated: false,
    confidence: 0.9,
    url: '《明史·庄烈帝纪》',
    tags: ['崇祯', '阉党', '魏忠贤'],
  },
  {
    claim: '崇祯十七年（1644）三月十九日，李自成率农民军攻破北京外城，翌日崇祯帝自缢。',
    entity: '李自成',
    source: 'rag',
    estimated: false,
    confidence: 0.9,
    url: '《明史·流贼传》',
    tags: ['崇祯', '李自成', '甲申'],
  },
  {
    claim: '崇祯二年（1629）己巳之变，皇太极绕道入京畿，兵临北京城下。',
    entity: '己巳之变',
    source: 'rag',
    estimated: false,
    confidence: 0.85,
    url: '《明史·庄烈帝纪》',
    tags: ['皇太极', '北京', '后金'],
  },
  {
    claim: '崇祯三年（1630），袁崇焕被磔死于市，时人有「自毁长城」之叹。',
    entity: '袁崇焕',
    source: 'rag',
    estimated: false,
    confidence: 0.9,
    url: '《明史·袁崇焕传》',
    tags: ['袁崇焕', '磔刑', '长城'],
  },
  {
    claim: '明末辽饷、剿饷、练饷三饷加派，民变蜂起，李自成、张献忠并兴。',
    entity: '三饷',
    source: 'rag',
    estimated: true,
    confidence: 0.7,
    basis: '按《明史·食货志》对加派与农民起义的总体叙述归纳',
    url: '《明史·食货志》',
    tags: ['三饷', '加派', '民变'],
  },
  {
    claim: '崇祯在位十七年，猜忌苛察、任事者难，国库存粮不足一年用度。',
    entity: '崇祯朝',
    source: 'rag',
    estimated: true,
    confidence: 0.6,
    basis: '据《明史》诸传对崇祯朝财政困局之通说的总体判断',
    url: '《明史》',
    tags: ['崇祯', '财政', '裁撤'],
  },
];

/** 途经店 · 一战（验收关键词：萨拉热窝、马恩河、凡尔登、停战） */
const WWI: PresetFact[] = [
  {
    claim: '1914年6月28日，奥匈帝国皇储斐迪南大公在萨拉热窝遇刺，成为第一次世界大战导火索。',
    entity: '斐迪南大公',
    source: 'rag',
    estimated: false,
    confidence: 0.95,
    url: '《全球通史·第一次世界大战》',
    basis: '通史通说',
    tags: ['一战', '萨拉热窝', '导火索'],
  },
  {
    claim: '1914年8月马恩河战役，德军速攻巴黎失败，西线陷入堑壕战僵局。',
    entity: '德军',
    source: 'rag',
    estimated: false,
    confidence: 0.85,
    url: '《一战与法国战场的静态战》',
    basis: '通史通说',
    tags: ['一战', '马恩河', '西线'],
  },
  {
    claim: '1916年凡尔登战役，德军围攻凡尔登，法军死守，双方伤亡逾百万。',
    entity: '法军',
    source: 'rag',
    estimated: false,
    confidence: 0.85,
    url: '《凡尔登战役研究》',
    basis: '通史通说',
    tags: ['一战', '凡尔登', '西线'],
  },
  {
    claim: '1918年11月11日，德国在康边森林签署停战协定，一战结束。',
    entity: '德军',
    source: 'rag',
    estimated: false,
    confidence: 0.9,
    url: '《停战协定档案》',
    basis: '通史通说',
    tags: ['一战', '停战', '德国'],
  },
{
    claim: '1914年8月，兴登堡与鲁登道夫在东线坦能堡战役大败俄军，成为一战名将。',
    entity: '兴登堡',
    source: 'rag',
    estimated: false,
    confidence: 0.85,
    url: '《坦能堡战役战史》',
    basis: '通史通说',
    tags: ['一战', '东线', '坦能堡'],
  },
];

/** 二战（欧洲战场：人物为政权代表/指挥官，勿用无人物义实体当立场人） */
const WWII: PresetFact[] = [
  {
    claim: '1939年9月1日，希特勒下令德军闪击波兰，英法对德宣战，二战全面爆发。',
    entity: '希特勒',
    source: 'rag',
    estimated: false,
    confidence: 0.95,
    url: '军史通说',
    tags: ['二战', '波兰', '闪击战'],
  },
  {
    claim: '1941年6月22日，希特勒撕毁《苏德互不侵犯条约》，德军突袭苏联，东线开战。',
    entity: '希特勒',
    source: 'rag',
    estimated: false,
    confidence: 0.9,
    url: '《苏德战争史》',
    tags: ['二战', '苏联', '东线'],
  },
  {
    claim: '1943年2月2日，斯大林格勒战役结束，苏军围歼德国第6集团军，东线转折点。',
    entity: '苏军',
    source: 'rag',
    estimated: false,
    confidence: 0.9,
    url: '《斯大林格勒战役》',
    basis: '通说：轴心国在斯大林格勒伤亡40万上',
    tags: ['二战', '苏联', '转折点'],
  },
  {
    claim: '1944年6月6日，艾森豪威尔任盟军最高统帅，指挥诺曼底登陆，开辟第二战场。',
    entity: '艾森豪威尔',
    source: 'rag',
    estimated: false,
    confidence: 0.9,
    url: '《艾森豪威尔回忆录》',
    tags: ['二战', '诺曼底', '第二战场'],
  },
  {
    claim: '1945年5月8日，德国无条件投降，欧洲战事结束。',
    entity: '德军',
    source: 'rag',
    estimated: false,
    confidence: 0.95,
    url: '《二战终结史录》',
    tags: ['二战', '欧战结束'],
  },
  {
    claim: '1942年8月起，朱可夫指挥斯大林格勒方面军死守巷战，至1943年2月围歼德军第6集团军。',
    entity: '朱可夫',
    source: 'rag',
    estimated: false,
    confidence: 0.85,
    url: '《朱可夫回忆录》',
    tags: ['二战', '斯大林格勒', '东线'],
  },
];

export const PRESET_FACTS: PresetFact[] = [
  ...CHONGZHEN,
  ...THREE_KINGDOMS,
  ...WANG_ANSHI,
  ...ANSHI,
  ...WWI,
  ...WWII,
];